# Leyendo archivos con Python

In [4]:
INPUT_FILE_PATH = '/content/drive/MyDrive/Datasets/datalake/datalake_inputs/netflix_titles.csv'
OUTUT_FILE_PATH_PY = '/content/drive/MyDrive/Datasets/datalake/datalake_outputs/netflix_titles_py.csv'

In [9]:
# Lectura linea x linea
with open(INPUT_FILE_PATH, 'r', encoding='utf-8') as f:
  for linea in f:
    print(linea.strip())
    break

duration_minutes,duration_seasons,type,title,date_added,release_year,rating,description,show_id

In [10]:
# Lectura todas las lineas (Como lista)
with open(INPUT_FILE_PATH, 'r', encoding='utf-8') as f:
  lineas = f.readlines()

lineas[:3]

['duration_minutes,duration_seasons,type,title,date_added,release_year,rating,description,show_id\n',
 '90,,Movie,Norm of the North: King Sized Adventure,2019-09-09 00:00:00,2019.0,TV-PG,"Before planning an awesome wedding for his grandfather, a polar bear king must take back a stolen artifact from an evil archaeologist first.",81145628.0\n',
 '94,,Movie,Jandino: Whatever it Takes,2016-09-09 00:00:00,2016.0,TV-MA,"Jandino Asporaat riffs on the challenges of raising kids and serenades the audience with a rousing rendition of ""Sex on Fire"" in his comedy show.",80117401.0\n']

In [8]:
with open(OUTUT_FILE_PATH_PY, 'w', encoding='utf-8') as f:
  for linea in lineas[:3]:
    f.write(linea)

# Leyendo archivos con pandas

In [2]:
import pandas as pd

In [4]:
df_csv = pd.read_csv('/content/drive/MyDrive/Datasets/datalake/datalake_inputs/netflix_titles.csv')

In [5]:
df_csv.to_csv('/content/drive/MyDrive/Datasets/datalake/datalake_outputs/netflix_titles.csv', index=False)

In [6]:
df_csv.head(2)

,duration_minutes,duration_seasons,type,title,date_added,release_year,rating,description,show_id
0,90,NaN,Movie,Norm of the North: King Sized Adventure,2019-09-09 00:00:00,2019.0,TV-PG,Before planning an awesome wedding for his gra...,81145628.0
1,94,NaN,Movie,Jandino: Whatever it Takes,2016-09-09 00:00:00,2016.0,TV-MA,Jandino Asporaat riffs on the challenges of ra...,80117401.0

# Total por campo

In [18]:
df_csv['type'].value_counts()

type
Movie      4265
TV Show    1969
1944          1
Name: count, dtype: int64

In [7]:
df_csv['duration_seasons'].value_counts()

duration_seasons
1                      1321
2                       304
3                       158
4                        61
5                        46
6                        22
7                        21
8                        16
9                         7
10                        3
11                        3
15                        2
12                        2
13                        2
2017-03-31 00:00:00       1
80188902                  1
14                        1
Name: count, dtype: int64

# Total por campo, considerando nulos

In [8]:
df_csv['duration_seasons'].value_counts(dropna=False)

duration_seasons
NaN                    4265
1                      1321
2                       304
3                       158
4                        61
5                        46
6                        22
7                        21
8                        16
9                         7
10                        3
11                        3
15                        2
12                        2
13                        2
2017-03-31 00:00:00       1
80188902                  1
14                        1
Name: count, dtype: int64

# Manejando nulos

## Como Ingeniero de datos, que hacemos con los datos nulos?

In [17]:
df_csv['duration_seasons'] = df_csv['duration_seasons'].fillna('1')
df_csv['duration_seasons'].value_counts()

duration_seasons
1                      5586
2                       304
3                       158
4                        61
5                        46
6                        22
7                        21
8                        16
9                         7
10                        3
11                        3
15                        2
12                        2
13                        2
2017-03-31 00:00:00       1
80188902                  1
14                        1
Name: count, dtype: int64

# Fecha de actualización

In [19]:
from datetime import datetime

In [20]:
df_csv.head(2)

,duration_minutes,duration_seasons,type,title,date_added,release_year,rating,description,show_id
0,90,1,Movie,Norm of the North: King Sized Adventure,2019-09-09 00:00:00,2019.0,TV-PG,Before planning an awesome wedding for his gra...,81145628.0
1,94,1,Movie,Jandino: Whatever it Takes,2016-09-09 00:00:00,2016.0,TV-MA,Jandino Asporaat riffs on the challenges of ra...,80117401.0

In [26]:
df_csv.to_csv('/content/drive/MyDrive/Datasets/datalake/datalake_outputs/netflix_titles.csv', index=False)

## Cuando recibimos la data?

In [21]:
df_csv['fecupdate'] = datetime.now()

In [22]:
df_csv.head(2)

,duration_minutes,duration_seasons,type,title,date_added,release_year,rating,description,show_id,fecupdate
0,90,1,Movie,Norm of the North: King Sized Adventure,2019-09-09 00:00:00,2019.0,TV-PG,Before planning an awesome wedding for his gra...,81145628.0,2026-04-29 01:54:18.886600
1,94,1,Movie,Jandino: Whatever it Takes,2016-09-09 00:00:00,2016.0,TV-MA,Jandino Asporaat riffs on the challenges of ra...,80117401.0,2026-04-29 01:54:18.886600

# Zona horaria

In [23]:
import pytz
peru_tz = pytz.timezone('America/Lima')

In [24]:
df_csv['fecupdate'] = datetime.now(peru_tz)

In [25]:
df_csv.head(2)

,duration_minutes,duration_seasons,type,title,date_added,release_year,rating,description,show_id,fecupdate
0,90,1,Movie,Norm of the North: King Sized Adventure,2019-09-09 00:00:00,2019.0,TV-PG,Before planning an awesome wedding for his gra...,81145628.0,2026-04-28 20:57:08.533628-05:00
1,94,1,Movie,Jandino: Whatever it Takes,2016-09-09 00:00:00,2016.0,TV-MA,Jandino Asporaat riffs on the challenges of ra...,80117401.0,2026-04-28 20:57:08.533628-05:00

# Python en Ingeniería de datos

In [ ]:
"""
Pasos:
1. Definir Parametros
2. Crear carpetas si no existen
3. Validar si existe el archivo
4. Limpiar directorio
5. Leer y guardar datos
"""

In [27]:
def hola():
  print('Hola mundo')

In [28]:
hola()

Hola mundo

In [31]:
def suma(a, b):
  return a+b

In [32]:
def main():
  hola()
  resultado = suma(1,2)
  print('El resultado es', resultado)
  print('Paso 1')
  print('Paso 2')

In [33]:
main()

Hola mundo
El resultado es 3
Paso 1
Paso 2

# Ejecución de una función SÓLO cuando se llama directamente
Si \__name__ no se iguala a \__main__, cada vez que se importe la librería, se llamará a la función

In [34]:
if __name__ == "__main__":
    main()

Hola mundo
El resultado es 3
Paso 1
Paso 2

In [ ]:
"""
- utils/
  datos_func.py (hola)
- test.py

=== Llamando funcion hola en test.py
from utils.datos_func import hola
hola()

# Si no encapsulo main() dentro de "if __name__ =...", se llamará a main() cada vez que se importe la función
"""